apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ufbank-ingress
  namespace: ufbank
  labels:
    app: ufbank
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ufbank.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ufbank-service
            port:
              number: 80
